[gsheets]
# Link da sua planilha (URL)
spreadsheet_url = "https://docs.google.com/spreadsheets/d/1-HBfc9So-Rx1HgbuTHpALXFz8NbhL7Z28zyN-zCkTAg/edit?usp=drivesdk"

# E-mail de Serviço (client_email)
client_email = "sistemas-de-vendas@digital-layout-473717-s3.iam.gserviceaccount.com"

# ID da Chave Privada (private_key_id)
private_key_id = "92984bafb089ba9488f5d57cf9dc911b3ce2ca09"

# Token URI (padrão)
token_uri = "https://oauth2.googleapis.com/token"

# Chave Privada (private_key) - O trecho mais longo (MUITO IMPORTANTE MANTER O FORMATO!)
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9LdL5+ohKCsK7
4xinkjxlhe35m8nZ4wgsrCEZVVfcdvn46wG8Q9dNK08j37DusK8eRNC7czSi4Swy
smJ2VqfWz17wJUwjSpGSHtvXe7692F50jFUB4gqZUzLDNEnOlf2KilBWfNTt5nfd
0jb9iFW89NkF4TRDmF9znnMR+iqaM9sJgotE06vHsvhWbkDcLEIgmaDnVXzxmU/S
xfFTwXYwuzvjrgTVMXjk3JG4wAJahhnC7LcWkb6NgnOIsLFux2IIz9I5K/PjvMGp
Cg3EZBgyZvqOmQno1X4XtkwDmp/4FrEZz13KyPAe+yXW3H62+L1gMlki+MK/HI/a
jM9Za383AgMBAAECgYkAFQkdZpKHHm89NsKKeJz4KPR61ms48gjJWz5LR+fc0d+g
7XQkSJeP6egg8ATq8FT72Up0SK5cx1JxJF9VjNcXPqQ8aEjywxHYR1Pgb4DhCsxz
uaieYzaL+ynsgRbgBiADhf4vRLleFpNZTMnCjO/gqMGJHZrsbCprTWNBua6u7LUa
OpA9RaYfFnjB3wesxGd8fBkwA9juAkADaqZGU2se4LEXRxsqIjvGSYowChCLKrmf
+zIm1QrqVeYX27JR7+vf8SixQIMB2vUqfGaadCr5SjfHQk4lFVR3zBoqfZQgeE3q
LXyUn48YVrqZ9jZ7mkP0HKwLqMp7UJ2NBxw64lhJoQKBgQDzkAJX+9Un7GVekib2
bAJqHd3JOeY0W+gNdX0VzsNu/+ZFJdTxv4vYwWDKnKtzdOkUPJWZ7GAIMjMFNGyJ
0d7KrXf9iHZM6abZLA0bQFToyzAHqw81rptfR3fe5g85EgQcSRWRkeZ5Dw8SbtHj
uT+Trc5k6dhI9iMFswPaR6nM2QKBgQDG1uG/tpKSTyReu7kMC6MyTtXtj9iPUUJt
Av1FgQ3HcvhUG9a8Yf+J4//nF5Axqmd1oQ6zDit1LLasWgtr/WFw+4jVa7rKq24U
RlXRd5LGlPZmNENtewWA8fIsrG3wN189gSqDN+Mx1wa5/C2rzbSJNBszcz/atCvP
jAgCTf9ijwKBgQCKbc7nMrpzdmgm1+pNJBY7Ob5UIBQ2rgW1oJD3VAy/ibHWmyns
PHG/QClC/shzVn8igUyFr1LlVaKp0qHdsuptRyprbqPOEv5BcEgCtQ2NQe6KbS63
1AV6oaP/i8IbLaIocWFQ2xuismxejZ29UAxSYvZrZH0I+tvs4VHPPevEAQKBgG5r
Yg3+q0KIpJ/fC5H+3G/Ri8dS/GYKMCMtZ8yzMB20YOcEVqlimm/Op4uDcFXEVZPj
DrCsi8GURRVNI86idPwzEvfBzYdCz+x+aqXaCy4wBu0W1OL1UEcdFOluD9c4SLF1
C1C3Nnm0+U1LF2my4DDZOMnHlIw1RacKEmCFQ+9NAoGBAPIhKXlhnZR8k6lYr/zO
/oMbEaf90+2EBpilaU/ro+Cn3UG7VprXJGCWOSU5xQZmMDsZlSB9Y4rp7Z7O9og9
hA3bpJfhenChH6bClCxAc6NtG4MRwWTg1mqaXwIt7mH9b0I0QKOZDeN/74LwmNEb
BC9kT14uwdgQH9E8uPwwj5fv
-----END PRIVATE KEY-----\n"""
